stop();
var color = 16777215;
var alpha = 0.6;
var blurX = 35;
var blurY = 35;
var strength = 2;
var quality = 3;
var inner = true;
var knockout = false;
var filter = new flash.filters.GlowFilter(color,alpha,blurX,blurY,strength,quality,inner,knockout);
var filterArray = new Array();
filterArray.push(filter);
var handDown = 0;
var myMode = 0;
var minuteClick = true;
var handClick = true;
var minuteRandom = 0;
var hourRandom = 0;
var randomMinute = 0;
var randomHour = 0;
var mySound = new Sound();
mySound.attachSound("bgmusic05.wav");
var myStart = new Sound();
myStart.attachSound("開始玩");
var myWin = new Sound();
myWin.attachSound("bababa");
var myRollOver = new Sound();
myRollOver.attachSound("按鈕.WAV");
var myTrue = new Sound();
myTrue.attachSound("正確");
mySound.start(2,1000);
Mouse.hide();
var mouseListener = new Object();
mouseListener.onMouseMove = function()
{
   star._x = _xmouse;
   star._y = _ymouse;
};
Mouse.addListener(mouseListener);
stop();
