on(press){
   bb.gotoAndStop(5);
   my_os1.stop();
   my_os2.stop();
   my_os3.stop();
   my_os4.stop();
   my_os5.stop();
   my_os6.stop();
   my_os7.stop();
   my_os8.stop();
   my_os9.stop();
   my_os8.start();
}
